### ISSUE TITLE
Error starting cannot touch /usr/local/bin

### ISSUE THREAD

**Issue by austincunningham** [austincunningham/change_oc#26]
# Error on start
touch: cannot touch '/usr/bin/oc': No such file or directory
child_process.js:651
    throw err;
    ^

Error: Command failed: sudo touch /usr/bin/oc
touch: cannot touch '/usr/bin/oc': No such file or directory

    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at Object.<anonymous> (/home/austin/repo/change_oc/index.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)

**Comment by austincunningham** [comment]
looks like this is related to https://github.com/austincunningham/change_oc/issues/25 , if the destination of the sim link is deleted you can't touch the file

**Comment by austincunningham** [comment]
work around `sudo rm /usr/bin/oc`

**Comment by austincunningham** [comment]
fix in https://github.com/austincunningham/change_oc/pull/36
