### ISSUE TITLE
Could not install oc 4.3

### ISSUE THREAD

**Issue by craicoverflow** [austincunningham/change_oc#51]
I got an error trying to install oc 4.3. Note that 4.1 worked fine.

```shell
download version:  4.3
tar (child): 4.3.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
child_process.js:669
    throw err;
    ^

Error: Command failed: tar --warning=no-unknown-keyword -C 4.3 -zxvf 4.3.tar.gz
tar (child): 4.3.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at /home/ephelan/.npm/_npx/250271/lib/node_modules/change_oc/src/extract.js:23:7
    at suppressedCallback (fs.js:215:5)
    at FSReqCallback.oncomplete (fs.js:156:23) {
  status: 2,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(187) [Uint8Array] [
      116,  97, 114,  32,  40,  99, 104, 105, 108, 100,  41,  58,
       32,  52,  46,  51,  46, 116,  97, 114,  46, 103, 122,  58,
       32,  67,  97, 110, 110, 111, 116,  32, 111, 112, 101, 110,
       58,  32,  78, 111,  32, 115, 117,  99, 104,  32, 102, 105,
      108, 101,  32, 111, 114,  32, 100, 105, 114, 101,  99, 116,
      111, 114, 121,  10, 116,  97, 114,  32,  40,  99, 104, 105,
      108, 100,  41,  58,  32,  69, 114, 114, 111, 114,  32, 105,
      115,  32, 110, 111, 116,  32, 114, 101,  99, 111, 118, 101,
      114,  97,  98, 108,
      ... 87 more items
    ]
  ],
  pid: 250356,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(187) [Uint8Array] [
    116,  97, 114,  32,  40,  99, 104, 105, 108, 100,  41,  58,
     32,  52,  46,  51,  46, 116,  97, 114,  46, 103, 122,  58,
     32,  67,  97, 110, 110, 111, 116,  32, 111, 112, 101, 110,
     58,  32,  78, 111,  32, 115, 117,  99, 104,  32, 102, 105,
    108, 101,  32, 111, 114,  32, 100, 105, 114, 101,  99, 116,
    111, 114, 121,  10, 116,  97, 114,  32,  40,  99, 104, 105,
    108, 100,  41,  58,  32,  69, 114, 114, 111, 114,  32, 105,
    115,  32, 110, 111, 116,  32, 114, 101,  99, 111, 118, 101,
    114,  97,  98, 108,
    ... 87 more items
  ]
}
```

**Comment by austincunningham** [comment]
@craicoverflow  I can reproduce the issue. Will investigate.

**Comment by austincunningham** [comment]
Looks to be fixed with the changes for https://github.com/austincunningham/change_oc/pull/62

**Comment by austincunningham** [comment]
closing this
