### ISSUE TITLE
can't install 4.4 , 4.5, 4.6

### ISSUE THREAD

**Issue by austincunningham** [austincunningham/change_oc#61]
```bash
npm start

> change_oc@0.0.32 start /home/austincunningham/repo/change_oc
> node index.js

======================== Check for OC Version Installed =============================
The folowing versions of oc are installed at /opt/openshift
4.1
4.2
Installed
ocm

================================= Download OC =======================================
Do you wish to install an oc binary yes/no ? y
What version of oc do you wish to install ? 
 - 3.7
 - 3.9
 - 3.10
 - 3.11
 - 4.1
 - 4.2
 - 4.3
 - 4.4
 - 4.5
 - 4.6
4.6
                                                                               ====>
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/austincunningham/repo/change_oc/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! change_oc@0.0.32 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the change_oc@0.0.32 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/austincunningham/.npm/_logs/2021-05-26T10_45_51_578Z-debug.log
```

**Comment by austincunningham** [comment]
looks like a socket timeout
this works
https://stackoverflow.com/a/37946399/7767400

**Comment by austincunningham** [comment]
https://github.com/austincunningham/change_oc/pull/62
